#+title: Home
#+hugo_base_dir: ../
#+hugo_section: /
#+export_file_name: _index

Hello, and welcome to OpenSource Philosophy! My name is Vitus
Schäfftlein and I am a student of philosophy working as an
assistant for Professor Niko Strobach at the WWU Münster, Germany. My
interests predominantly lie in the philosophy of language, ontology and
logic. Apart from that, I am an advocate of the idea that knowledge as
well as the means to effectively accumulate and spread it should be accessible to anyone.

As its name suggests, this blog features topics concerning both
philosophy and open source software, and I have deliberately chosen it
to allow divergent interpretations as to what it actually is about. If
you are interested in learning more about that, feel free to look into
this post. If you happen to be interested in who I am, what I do, why
I do it and what I want to do in the future, you are invited to have a
look at the About Me section. If you like what you see and you want to support me, this post is for you.
