#+title: Example Post
#+date: <2022-01-27 Thu 13:49>
#+hugo_base_dir: ../
#+hugo_section: posts
#+hugo_type: post
#+hugo_custom_front_matter: :tikzjax true
#+hugo_lastmod: <2022-01-28 Fri 14:00>
#+hugo_tags: test example "syntax highlighting" 
#+filetags: :noexport:
#+csl-style: ../static/apa.csl
#+csl-locale: en-US

#+description: This post is an example of org-mode syntax highlighting being exported to hugo markdown.

* Markup
Is this *bold*? Is this /italic/? Is this _underlined_? Is this =verbatim=? Is this ~Ctrl+A~? Is this +struck through+?

And now, a deterministic proof: Sed diam.  Sed bibendum.  Pellentesque tristique imperdiet tortor.  

I'd also like to link to a [[/Downloads/[Linux] notes.el][file]]. [[/Downloads/\[Linux\] notes.el][file]] 
* Special Blocks
#+begin_mark
This is an example custom block.
#+end_mark

** TODO Details
Details are nice.

* Source Code
** Elisp
#+begin_src elisp
(defun get-things-working ()
"Get things working!"
(and (my-custom-function) (another-function)))
#+end_src

** Latex
#+begin_src latex
\begin{document}
\titlepage
\end{document}
#+end_src

* LaTeX Highlighting
Examples of inline[fn:2] math formulae: $\rm{ax^{2}+bx+c}$, \(\rm{p \  \to q \lor r}\).

Examples of block equations:

$\rm{p \to q \lor r}$


* Table of contents
#+toc: headlines 2
* TikzJax Rendered SVGs
Here's a picture of a circle.
<<circle>>
#+attr_html: :caption A cool circle.
#+begin_tikzjax
\draw[red] (0,0) circle (1in);
#+end_tikzjax

A link to the[fn:1] [[circle][circle]].

* Citing
Here are some cite commands I may want to use:

| *cite command* | *result*                 |
|--------------+------------------------|
| cite         | [[cite:&howard1998]]       |
| parencite    | [[parencite:&howard1998]]  |
| citeauthor   | [[citeauthor:&howard1998]] |
| citeyear     | [[citeyear:&howard1998]]   |
| citetitle    | citetitle:&howard1998  |

#+BEGIN_EXPORT html
<p>You can also create a new document by pressing <kbd><kbd class="key">Ctrl</kbd>+<kbd class="key">N</kbd></kbd>.</p>

<kbd class="key">code</kb>
#+END_EXPORT



[[cite:&howard1998]]


[[bibliography:../static/blog.bib]]

* Footnotes

[fn:2] Footnote! 

[fn:1] And this is another footnote. 
