baseURL="//Perangelot.github.io"
theme="hugo-theme-hello-friend"
languageCode = "en-us"

title = "opensource-philosophy"
subtitle="A philosopher's blog"
description="Philosophy, Logic, and Open Source"

linenos = true

lastModDisplay = "Modified last on"
enableGitInfo=true
[languages.en.params.logo]
  logoText = "opensource-philosophy"
  logoHomeLink = "/"
# or
#
# path = "/img/your-example-logo.svg"
# alt = "Your example logo alt text"

[params]
# if you set this to 0, only submenu trigger will be visible
showMenuItems = 2
menuMore = "More"

enableGitInfo = true
lastmod = ":git"
publishDate = 'publishDate'
dateFormatSingle = "Jan 02, 2006"
dateFormatList = "Jan 02, 2006"

# Menus

[languages.en.menu]

[[languages.en.menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[languages.en.menu.main]]
identifier = "Posts"
name = "Posts"
url = "/posts/"
weight = 2


[[languages.en.menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects/"
weight = 3

[[languages.en.menu.main]]
identifier = "about"
name = "About Me"
url = "/about/"
weight = 4
[[languages.en.menu.main]]
identifier = "donate"
name = "Donate"
url = "/donate/"
weight = 5

[[languages.en.menu.main]]
identifier = "logic"
name = "Logic"
url = "/logic/"
parent = "posts"

[[languages.en.menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
parent = "/"

# Tags and Categories
[taxonomies]
tag="tags"
category="categories"
