baseURL="Perangelot.github.io"
theme="hugo-theme-hello-friend"
languageCode = "en-us"
title = "opensource-philosophy"
subtitle="A philosopher's blog"
description="Philosophy, Logic, and Open Source"
[languages.en.params.logo]
  logoText = "opensource-philosophy"
  logoHomeLink = "/"
# or
#
# path = "/img/your-example-logo.svg"
# alt = "Your example logo alt text"

