#+title: Example
#+date: 2022-01-20
#+hugo_base_dir: ../
#+hugo_type: post
#+filetags: emacs LaTeX

* Description                                                        :ignore:
#+begin_description
Here is my *post summary*.


Hello, and welcome to OpenSource Philosophy! I am Vitus Schäfftlein, an undergraduate student with a deep-rooted passion for philosophy -- and an advocate of the idea that academia should be open source, not least because at the heart of both democratic societies and academia, there is freedom and knowledge, which are two concepts that cannot and must not be ripped apart.
#+end_description


 
* Markup
Is this *bold*?
Is this /in italics/?
Is this _underlined_?
Is this =verbatim=?
Is this ~code~?
Is this +strike-through+?

#+begin_mark
This sentence is marked.
#+end_mark

* Special Blocks
Oh look some special block content.

#+begin_BLOCKTAG
something
#+end_BLOCKTAG
#+begin_aside
Some content for the ~aside~ block.
#+end_aside
#+begin_details
#+begin_summary
This is summary.
#+end_summary
Here are the details.
#+end_details

#+begin_tikzjax
\draw (0,0) circle (1in);
#+end_tikzjax
#+begin_katex
E = -J \sum\_{i=1}^N s\_i s\_{i+1}
#+end_katex
* TODO Attachments

* Linking
Does this link to [[LaTeX][LaTeX]]?
See the [[http://localhost:1313/][main page]]
* Referencing
#+BEGIN_QUOTE
This is just a random attempt at looking whether the =quote= environment works.
#+END_QUOTE
[[cite:&zermelo2010]]
* LaTeX
** Inline Formuals
$r \lor a$
$lel$
$p \to q$ 
$q \to r$
** Source Blocks
#+BEGIN_EXPORT latex
\Latex \LaTeX anything?
#+END_EXPORT
Did anything get printed?


* Source Code
** Elisp
#+begin_src elisp
(defun get-things-working ()
"Get things working!"
(and (my-custom-function) (another-function)))
#+end_src

** LaTeX
#+BEGIN_src LaTeX
\begin{document}
\titlepage
\end{document}
#+END_src
** Try

#+BEGIN_EXPORT html
<pre>
\begin{document}
\titlepage
\end{document}
</pre>
   #+END_EXPORT



* Tables
Is this exported as an html table?

| / | < |           | < |                  | < |              |   |
|   |   | Uhrzeit   |   | Altklausur       |   | Tutor:in     |   |
|---+---+-----------+---+------------------+---+--------------+---|
|   |   | 10-12 Uhr |   | Altklausur 16/17 |   | Luca, Marvin |   |
|   |   | 12-14 Uhr |   | Altklausur 17/18 |   | Tobias       |   |
|   |   | 14-16 Uhr |   | Altklausur 18/19 |   | Lena         |   |
|   |   | 16-18 Uhr |   | Altklausur 19/20 |   | Vitus        |   |

| And  | this | table? |
|------+------+--------|
| Try  | out  | here   |
| next | line |        |


* Syntax Highlighting
#+begin_src python
import os

print("Oh Hi Mark")
x = 3
x = x+2
print("What Is X?")
print("x=5")
#+end_src

* Local Variables                                                  :noexport:
Local Variables:
org-preview-latex-image-directory: "/home/vitus/Schreibtisch/hugo/imgs"
flyspell-mode: t
End:

